### ISSUE TITLE
Information about AS' is hidden even at DEBUG-level

### ISSUE THREAD

**Issue by einar** [dotse/zonemaster-cli#24]
It should be possible to see all available data on AS-numbers when running at DEBUG level; as it is now the only information available (regardless of level) is the number/name itself and not the network or operator. This is from DNSCheck (something similar should be implemented in Zonemaster):
  3.338: DEBUG [ASN:RAW] 85.24.141.132;8473 | 85.24.128.0/18 | SE | ripencc | 2005-02-24
  3.341: DEBUG [ASN:ANNOUNCE_BY] 85.24.141.132;8473
  3.342: DEBUG [ASN:ANNOUNCE_IN] 85.24.141.132;85.24.128.0/18

While Zonemaster, at level DEBUG, only says:
   2.34 INFO      CONNECTIVITY:NAMESERVER_HAS_TCP_53 address=85.24.141.132, ns=ns1.rayceem.com
   5.64 INFO      CONNECTIVITY:IPV4_ASN asn=8473
   5.64 INFO      CONNECTIVITY:IPV6_ASN asn=
   5.64 WARNING   CONNECTIVITY:NAMESERVERS_IPV4_WITH_UNIQ_AS asn=8473

This is not a bug but it is a feature request for us data miners. :)

**Comment by sandoche2k** [comment]
@vlevigneron - logging AS numbers
