### ISSUE TITLE
Version information contains superfluous "v"

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster-cli#33]
When the cli is asked for version information, it returns:

```
$ zonemaster-cli --version
CLI version:    v1.0.5
Engine version: v1.0.15
```

It's obvious that the numbers are version numbers, and don't need a "v" before them. Most other software reports its version as X.Y.Z, and there is no need for a "v" before it. Please consider reporting the version number in a way that most other software reports it.

**Comment by sandoche2k** [comment]
@matsduf Need this update https://github.com/dotse/zonemaster/issues/465 to close this issue

**Comment by sandoche2k** [comment]
Refer to https://github.com/dotse/zonemaster/issues/461
