### ISSUE TITLE
Remove dependency of gettext binary at build time

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-cli#45]
At installation, the *.po (locale translation files) are converted to the equivalent *.mo files and put in the correct locale directory, but only if the binary msgfmt is available. The conversion must be done at installation time since it is architecture dependent.

Use perl library Locale::Msgfmt instead to get rid of the dependency.

See https://github.com/dotse/zonemaster-engine/pull/305

**Comment by sandoche2k** [comment]
Closed by PR https://github.com/dotse/zonemaster-cli/pull/52
