### ISSUE TITLE
DNSSEC signature expire

### ISSUE THREAD

**Issue by tobbe-eklov** [dotse/zonemaster-cli#6]
Hi, I miss the DNSSEC signature expire who dnscheck prints out.

Example from dnscheck
INFO DNSSEC signature expires at: Fri Mar  6 15:35:01 2015

It would be nice to have it printed out when in 
--level INFO --raw 
mode and with SOA and DNSKEY's separate printed out

And if expire for NS, MX and ev. www RR also is printed out it's great!
  
/Tobbe

**Comment by pawal** [comment]
This issue was moved to dotse/zonemaster-engine#13
