### ISSUE TITLE
Translation on FreeBSD (CLI)

### ISSUE THREAD

**Issue by mattias-p** [dotse/zonemaster-cli#64]
On FreeBSD the `--locale` parameter is ignored. Instead the translation language is determined from the `LC_ALL`, `LC_MESSAGES` and `LANG` environment variables.

See issue #46.

**Comment by mattias-p** [comment]
The cause for this is analogous to https://github.com/dotse/zonemaster-backend/issues/353.

**Comment by sandoche2k** [comment]
If it is a freeBSD *only* issue, then #46 should be closed

**Comment by matsduf** [comment]
Please, #46 is about Ubuntu, Debian and CentOS.

**Comment by sandoche2k** [comment]
https://github.com/dotse/zonemaster-cli/pull/71

**Comment by sandoche2k** [comment]
closing due to PR #71
